package com.medinexz.notenoughresources.integration.thermalfoundation;

import com.medinexz.notenoughresources.integration.INERIntegration;
import com.medinexz.notenoughresources.integration.IntegrationHelper;

/**
 * Thermal Foundation (1.7.10) world generation resources.
 *
 * <p>Checked against Thermal Foundation 1.2.6: its ores are generated by CoFH Core
 * from the world generation file the mod ships (and the user can edit): copper,
 * tin, silver, lead, nickel and platinum ore, with some lead in silver veins
 * and nickel in platinum veins.  Mana infused ore is not generated.</p>
 */
public class ThermalFoundationIntegration implements INERIntegration {

    private static final String MOD_ID = "ThermalFoundation";

    private static final int OVERWORLD = 0;

    // "Ore" block variants: copper, tin, silver, lead, nickel, platinum
    private static final int GENERATED_ORES = 6;

    @Override
    public String getModId() {
        return MOD_ID;
    }

    @Override
    public void registerResources() {
        for (int ore = 0; ore < GENERATED_ORES; ore++) {
            IntegrationHelper.register(MOD_ID, "Ore", ore, OVERWORLD);
        }
    }
}
