package com.medinexz.notenoughresources.integration.thaumcraft.addons;

import com.medinexz.notenoughresources.integration.INERIntegration;

/**
 * Gadomancy (1.7.10).
 *
 * <p>Checked against Gadomancy 1.0.7.3: no world generation.  The mod registers
 * its own copy of the Outer Lands, in which a maze is built for each player
 * who enters through the Node Manipulator, not generated by chunk.</p>
 */
public class GadomancyIntegration implements INERIntegration {

    private static final String MOD_ID = "gadomancy";

    @Override
    public String getModId() {
        return MOD_ID;
    }

    @Override
    public void registerResources() {
        // No world generation in this addon
    }
}
